apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-management
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/skncvo/infra-repo.git
    targetRevision: main
    path: devops-platform/platform/gitlab
  destination:
    server: https://kubernetes.default.svc
    namespace: cicd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
