- hosts: k8s_master
  become: yes
  tasks:
    - name: Check API server readiness
      command: kubectl --kubeconfig=/etc/kubernetes/admin.conf get nodes
      register: kubectl_nodes_check
      changed_when: false

    - name: Copy ingress values
      copy:
        src: ../roles/ingress_nginx/files/values.yaml
        dest: /tmp/ingress-values.yaml
        owner: root
        group: root
        mode: '0644'

    - name: Add ingress-nginx helm repo
      command: >
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

    - name: Update helm repos
      command: helm repo update

    - name: Install ingress-nginx
      command: >
        helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx
        --kubeconfig /etc/kubernetes/admin.conf
        --namespace ingress-nginx
        --create-namespace
        -f /tmp/ingress-values.yaml
      register: ingress_install
      changed_when: >
        'STATUS: deployed' in ingress_install.stdout or
        'STATUS: upgraded' in ingress_install.stdout
